version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
          cache-version: v4
      - run: npm run build
  test:
    docker:
      - image: cimg/node:15.11.0-browsers
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
          cache-version: v4
      - run: npm run build-storybook
      - run: npm run test
      - run: npm run lint
workflows:
  build_and_test:
    jobs:
      - build
      - test
