export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const TOGGLE_TASK_STATE = "TOGGLE_TASK_STATE";
export const SHOW_ALL_TASKS = "SHOW_ALL_TASKS";
export const SHOW_ACTIVE_TASKS = "SHOW_ACTIVE_TASKS";
export const SHOW_COMPLETED_TASKS = "SHOW_COMPLETED_TASKS";
export const CLEAR_COMPLETED_TASKS = "CLEAR_COMPLETED_TASKS";
export const SWITCH_THEME = "SWITCH_THEME";